###############################################################################
# Created by write_sdc
###############################################################################
current_design hdc_chip
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name clk -period 20.0000 [get_ports {clk}]
set_clock_transition 0.1500 [get_clocks {clk}]
set_clock_uncertainty 0.2500 clk
set_propagated_clock [get_clocks {clk}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {feat_addr[0]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {feat_addr[1]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {feat_addr[2]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {feat_addr[3]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {feat_addr[4]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {feat_addr[5]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {feat_data[0]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {feat_data[1]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {feat_data[2]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {feat_data[3]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {feat_we}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {label[0]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {label[1]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {label[2]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ld_data[0]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ld_data[10]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ld_data[11]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ld_data[12]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ld_data[13]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ld_data[14]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ld_data[15]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ld_data[16]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ld_data[17]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ld_data[18]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ld_data[19]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ld_data[1]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ld_data[20]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ld_data[21]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ld_data[22]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ld_data[23]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ld_data[24]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ld_data[25]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ld_data[26]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ld_data[27]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ld_data[28]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ld_data[29]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ld_data[2]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ld_data[30]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ld_data[31]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ld_data[3]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ld_data[4]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ld_data[5]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ld_data[6]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ld_data[7]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ld_data[8]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ld_data[9]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ld_shift}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {learn}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {load_we}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rst}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {start}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {upd_err}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {busy}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {done}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {learned}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pred[0]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pred[1]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {pred[2]}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.0334 [get_ports {busy}]
set_load -pin_load 0.0334 [get_ports {done}]
set_load -pin_load 0.0334 [get_ports {learned}]
set_load -pin_load 0.0334 [get_ports {pred[2]}]
set_load -pin_load 0.0334 [get_ports {pred[1]}]
set_load -pin_load 0.0334 [get_ports {pred[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {clk}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {feat_we}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ld_shift}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {learn}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {load_we}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {rst}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {start}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {upd_err}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {feat_addr[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {feat_addr[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {feat_addr[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {feat_addr[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {feat_addr[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {feat_addr[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {feat_data[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {feat_data[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {feat_data[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {feat_data[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {label[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {label[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {label[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ld_data[31]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ld_data[30]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ld_data[29]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ld_data[28]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ld_data[27]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ld_data[26]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ld_data[25]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ld_data[24]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ld_data[23]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ld_data[22]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ld_data[21]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ld_data[20]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ld_data[19]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ld_data[18]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ld_data[17]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ld_data[16]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ld_data[15]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ld_data[14]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ld_data[13]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ld_data[12]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ld_data[11]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ld_data[10]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ld_data[9]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ld_data[8]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ld_data[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ld_data[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ld_data[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ld_data[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ld_data[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ld_data[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ld_data[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ld_data[0]}]
set_timing_derate -early 0.9500
set_timing_derate -late 1.0500
###############################################################################
# Design Rules
###############################################################################
set_max_transition 0.7500 [current_design]
set_max_capacitance 0.2000 [current_design]
set_max_fanout 10.0000 [current_design]
