"""Parameterized RTL generator for the ApproxHDC-Forge datapath (synthesizable Verilog-2005).

The generated module is a bit-exact implementation of hdc_model.py:

  * slice-serial: one P-bit slice of every hypervector per step, S = D / P slices
  * ID / level / tie / stochastic-mask vectors are regenerated by mix32 hash lanes
  * prototypes (learning off) or saturating counters (learning on) live in rings: one
    shift register of S words per design, rotated once per slice step, so the head word
    is always the current slice and no read mux is needed
  * pass 1 encodes + classifies, pass 2 (if learning) re-encodes and updates the ring head

Interface (all synchronous to clk, rst is synchronous and active high):
  feat_we/feat_addr/feat_data  write the F quantized features of the next sample
  start + learn + upd_err + label  run one sample (upd_err: 1 = error-driven, 0 = bundle-all)
  done (1-cycle pulse), pred, learned, dist_flat   result of the last sample
  load_we + load_data          shift one word into the ring tail (S writes load slices 0..S-1)
  rot                          rotate the ring by one word (S rotations = readout via head)
  head                         current ring head word: class c lane i at bits (c*P+i)*WS
  busy                         high during the post-reset clear and while a sample runs

    python rtlgen.py --D 512 --P 64 --variant trunc --knob 1 --learn 2 --w 4 --k 3 -o out.v
"""
import argparse
import json
import math
from dataclasses import asdict, dataclass

VARIANT_IDS = {"exact": 0, "trunc": 1, "satcomp": 2, "sampled": 3}
LEARN_MODES = {0: "off", 1: "bundle", 2: "error"}


@dataclass(frozen=True)
class RTLConfig:
    D: int = 512
    P: int = 64
    F: int = 64
    Q: int = 16
    C: int = 6
    variant: str = "exact"
    knob: int = 0
    learn: int = 0          # 0 off, 1 bundle-all only, 2 bundle-all + error-driven
    w: int = 8              # counter width (learn > 0)
    k: int = 0              # stochastic update exponent (learn > 0)
    seed: int = 0
    cg: int = 0             # 1 = clock-gate the ring memory (and the chip's load staging register)

    def __post_init__(self):
        assert self.D & (self.D - 1) == 0 and 32 <= self.D <= 4096, "D: power of 2 in 32..4096"
        assert self.P % 32 == 0 and self.D % self.P == 0, "P: multiple of 32 that divides D"
        assert 2 <= self.C <= 8 and 2 <= self.F <= 1023 and 2 <= self.Q <= 4096
        assert self.variant in VARIANT_IDS
        if self.variant == "sampled":
            assert (self.D * self.knob // 8) % self.P == 0 and 1 <= self.knob <= 8
        if self.learn:
            assert 2 <= self.w <= 16 and 0 <= self.k <= 4
        assert 0 <= self.seed <= 15 and self.cg in (0, 1)

    @property
    def S(self):
        return self.D // self.P

    @property
    def SC(self):  # slices compared in pass 1
        return self.D * self.knob // 8 // self.P if self.variant == "sampled" else self.S

    @property
    def name(self):
        s = f"hdc_D{self.D}_P{self.P}_F{self.F}_Q{self.Q}_{self.variant}{self.knob}_L{self.learn}"
        s = s + (f"_w{self.w}_k{self.k}" if self.learn else "")
        return s + ("_cg" if self.cg else "")


CG_MODULE = """// Clock gate. Synthesis (define HDC_SYNTH_ICG): the sky130 integrated clock-gating cell.
// Simulation: transparent-low latch + AND, the textbook model of the same cell.
`ifdef HDC_SYNTH_ICG
module hdc_cg (input wire clk, input wire en, output wire gclk);
  sky130_fd_sc_hd__dlclkp_1 u_icg (.CLK(clk), .GATE(en), .GCLK(gclk));
endmodule
`else
module hdc_cg (input wire clk, input wire en, output wire gclk);
  reg en_l;
  always @(*) if (!clk) en_l = en;
  assign gclk = clk & en_l;
endmodule
`endif
"""


def _clog2(n):
    return max(1, math.ceil(math.log2(n)))


def _group_expr(variant, knob):
    if variant == "trunc":
        return f"(c >> {knob})"
    if variant == "satcomp":
        m = (1 << knob) - 1
        return f"((c > 4'd{m}) ? 4'd{m} : c)"
    return "c"


def generate(cfg: RTLConfig, top="approxhdc_top"):
    D, P, F, Q, C, S, SC = cfg.D, cfg.P, cfg.F, cfg.Q, cfg.C, cfg.S, cfg.SC
    WS = cfg.w if cfg.learn else 1
    RW = C * P * WS
    LQ, LF, AF, AW, LS = _clog2(Q), _clog2(F), _clog2(F + 1), int(math.log2(D)) + 1, _clog2(S + 1)
    NW = P // 32
    lo, hi = -(1 << (WS - 1)), (1 << (WS - 1)) - 1
    thr_cases = "\n".join(f"      {LQ}'d{q}: thr = 12'd{q * 2048 // (Q - 1)};" for q in range(Q))
    if cfg.learn and cfg.k:
        mask_expr = " & ".join(f"mix32({{SEED, 2'd3, u, word4 + 16'd{i}}})" for i in range(cfg.k))
    else:
        mask_expr = "32'hFFFFFFFF"
    ring_shift = ("ring <= tail;" if S == 1 else f"ring <= {{tail, ring[{S * RW - 1}:{RW}]}};")
    if cfg.cg:   # ring on a gated clock: no per-bit hold multiplexer, no clock activity while it holds
        ring_always = f"wire gclk_ring;\n  hdc_cg u_cg_ring (.clk(clk), .en(shift), .gclk(gclk_ring));\n  always @(posedge gclk_ring) {ring_shift}"
    else:
        ring_always = f"always @(posedge clk) if (shift) {ring_shift}"
    cg_text = CG_MODULE + "\n" if cfg.cg else ""

    if cfg.learn:
        proto_lane = f"""
      wire signed [{WS-1}:0] cnt = head[(c*{P}+i)*{WS} +: {WS}];
      assign proto[c*{P}+i] = (cnt > 0) | ((cnt == 0) & tbit[i]);
      // learning update of this lane (used only in pass-2 commit)
      wire plus  = (c == lab_r);
      wire minus = err_r & (c == pred);
      wire up = qbit[i] ^ minus;
      wire signed [{WS}:0] nx = up ? cnt + 1 : cnt - 1;
      wire signed [{WS-1}:0] sat = (nx > {hi}) ? {hi} : (nx < {lo}) ? -{-lo} : nx[{WS-1}:0];
      assign upd[(c*{P}+i)*{WS} +: {WS}] = ((plus | minus) & mbit[i]) ? sat : cnt;"""
        tail_commit = "pass2 ? upd : head"
    else:
        proto_lane = f"""
      assign proto[c*{P}+i] = head[c*{P}+i];"""
        tail_commit = "head"

    return f"""// Generated by rtlgen.py -- do not edit. Config: {json.dumps(asdict(cfg))}
`default_nettype none
{cg_text}module {top} (
  input  wire              clk,
  input  wire              rst,
  input  wire              start,
  input  wire              learn,
  input  wire              upd_err,
  input  wire [2:0]        label,
  input  wire              feat_we,
  input  wire [{LF-1}:0]   feat_addr,
  input  wire [{LQ-1}:0]   feat_data,
  input  wire              load_we,
  input  wire              rot,
  input  wire [{RW-1}:0]   load_data,
  output wire [{RW-1}:0]   head,
  output wire              busy,
  output reg               done,
  output reg  [2:0]        pred,
  output reg               learned,
  output wire [{C*AW-1}:0] dist_flat,
  output wire [{P-1}:0]    dbg_q,
  output wire              dbg_commit,
  output wire              dbg_pass2
);
  localparam [3:0] SEED = 4'd{cfg.seed};
  localparam LEARN = {cfg.learn};

  // ------------------------------------------------------------------ hashing
  function [31:0] xs(input [31:0] x);
    reg [31:0] t;
    begin t = x ^ (x << 13); t = t ^ (t >> 17); xs = t ^ (t << 5); end
  endfunction
  function [31:0] mix32(input [31:0] x);
    begin mix32 = xs(xs(xs(x) + 32'h9E3779B9) + 32'h7F4A7C15); end
  endfunction
  function [3:0] grp(input [7:0] b);
    reg [3:0] c; integer n;
    begin
      c = 4'd0;
      for (n = 0; n < 8; n = n + 1) c = c + b[n];
      grp = {_group_expr(cfg.variant, cfg.knob)};
    end
  endfunction

  // ---------------------------------------------------------------- control
  localparam [2:0] IDLE = 3'd0, CLEAR = 3'd1, ENC = 3'd2, COMMIT = 3'd3, SKIP = 3'd4,
                   DECIDE = 3'd5, FIN = 3'd6;
  reg [2:0]      state;
  reg [{LS-1}:0] s;           // slice index
  reg [9:0]      f;           // feature index
  reg            pass2;
  reg [2:0]      lab_r;
  reg            learn_r, err_r;
  reg [9:0]      u;           // learning-event counter (stochastic mask key)
  reg [{AW-1}:0] dacc [0:{C-1}];
  reg [{LQ-1}:0] feat [0:{F-1}];

  assign busy = (state != IDLE);
  assign dbg_commit = (state == COMMIT);
  assign dbg_pass2 = pass2;

  always @(posedge clk) if (feat_we) feat[feat_addr] <= feat_data;

  // ------------------------------------------------- slice vectors (rematerialized)
  wire [{LQ-1}:0] lvl = feat[f[{LF-1}:0]];
  reg  [11:0] thr;
  always @* begin
    case (lvl)
{thr_cases}
      default: thr = 12'd0;
    endcase
  end

  wire [{P-1}:0] bnd, tbit, mbit;
  genvar gw, gb, gc, gi;
  generate for (gw = 0; gw < {NW}; gw = gw + 1) begin : g_word
    wire [15:0] word  = s * {NW} + gw;
    wire [15:0] word4 = word * 4;
    wire [31:0] hid = mix32({{SEED, 2'd0, f, word}});
    wire [31:0] hl0 = mix32({{SEED, 2'd2, 10'd0, word}});
    wire [31:0] ht  = mix32({{SEED, 2'd1, 10'd0, word}});
    wire [31:0] hm  = {mask_expr};
    for (gb = 0; gb < 32; gb = gb + 1) begin : g_bit
      wire [15:0] j16 = word * 32 + gb;
      wire [11:0] j = j16[11:0];
      wire [11:0] r = {{j[0],j[1],j[2],j[3],j[4],j[5],j[6],j[7],j[8],j[9],j[10],j[11]}};
      assign bnd[32*gw+gb]  = hid[gb] ^ hl0[gb] ^ (r < thr);
      assign tbit[32*gw+gb] = ht[gb];
      assign mbit[32*gw+gb] = hm[gb];
    end
  end endgenerate

  // ------------------------------------------------ encoder: bundle + majority
  reg  [{AF-1}:0] acc [0:{P-1}];
  wire [{P-1}:0]  qbit;
  generate for (gi = 0; gi < {P}; gi = gi + 1) begin : g_enc
    always @(posedge clk)
      if (state == ENC) acc[gi] <= (f == 10'd0 ? {AF}'d0 : acc[gi]) + bnd[gi];
    wire [{AF}:0] twice = {{acc[gi], 1'b0}};
    assign qbit[gi] = (twice > {F}) ? 1'b1 : (twice < {F}) ? 1'b0 : tbit[gi];
  end endgenerate
  assign dbg_q = qbit;

  // ------------------------------------------------ ring storage
  reg  [{S*RW-1}:0] ring;
  assign head = ring[{RW-1}:0];
  wire [{C*P-1}:0] proto;
  wire [{RW-1}:0]  upd;
  generate for (gc = 0; gc < {C}; gc = gc + 1) begin : g_cls
    for (gi = 0; gi < {P}; gi = gi + 1) begin : g_lane
      localparam integer c = gc, i = gi;{proto_lane}
    end
  end endgenerate

  wire shift = (state == CLEAR) | (state == COMMIT) | (state == SKIP) |
               (state == IDLE & (load_we | rot));
  wire [{RW-1}:0] tail = (state == CLEAR) ? {{{RW}{{1'b0}}}} :
                         (state == COMMIT) ? ({tail_commit}) :
                         (state == IDLE & load_we) ? load_data : head;
  {ring_always}

  // ------------------------------------------------ similarity (per class)
  wire [{C*AW-1}:0] sim_flat;
  generate for (gc = 0; gc < {C}; gc = gc + 1) begin : g_sim
    wire [{P-1}:0] x = qbit ^ proto[gc*{P} +: {P}];
    reg  [{AW-1}:0] sum; integer g;
    always @* begin
      sum = {AW}'d0;
      for (g = 0; g < {P // 8}; g = g + 1) sum = sum + grp(x[8*g +: 8]);
    end
    assign sim_flat[gc*{AW} +: {AW}] = sum;
    assign dist_flat[gc*{AW} +: {AW}] = dacc[gc];
  end endgenerate

  // argmin, lowest index wins ties
  reg [2:0] best; reg [{AW-1}:0] bestd; integer cc;
  always @* begin
    best = 3'd0; bestd = dacc[0];
    for (cc = 1; cc < {C}; cc = cc + 1)
      if (dacc[cc] < bestd) begin best = cc; bestd = dacc[cc]; end
  end

  integer ci;
  always @(posedge clk) begin
    done <= 1'b0;
    if (rst) begin
      state <= CLEAR; s <= 0; f <= 10'd0; pass2 <= 1'b0; u <= 10'd0;
      pred <= 3'd0; learned <= 1'b0;
    end else case (state)
      CLEAR: begin
        s <= s + 1'b1;
        if (s == {S - 1}) begin s <= 0; state <= IDLE; end
      end
      IDLE: if (start) begin
        lab_r <= label; learn_r <= learn; err_r <= upd_err & (LEARN == 2);
        s <= 0; f <= 10'd0; pass2 <= 1'b0; learned <= 1'b0;
        for (ci = 0; ci < {C}; ci = ci + 1) dacc[ci] <= {AW}'d0;
        state <= ENC;
      end
      ENC: begin
        f <= f + 1'b1;
        if (f == {F - 1}) state <= COMMIT;
      end
      COMMIT: begin
        f <= 10'd0;
        s <= s + 1'b1;
        if (!pass2) begin
          for (ci = 0; ci < {C}; ci = ci + 1)
            dacc[ci] <= dacc[ci] + sim_flat[ci*{AW} +: {AW}];
          if (s == {SC - 1}) state <= ({SC} < {S}) ? SKIP : DECIDE;
          else state <= ENC;
        end else begin
          if (s == {S - 1}) begin u <= u + 1'b1; learned <= 1'b1; state <= FIN; end
          else state <= ENC;
        end
      end
      SKIP: begin
        s <= s + 1'b1;
        if (s == {S - 1}) state <= DECIDE;
      end
      DECIDE: begin
        pred <= best;
        s <= 0; f <= 10'd0;
        if (LEARN != 0 && learn_r && (!err_r || best != lab_r)) begin
          pass2 <= 1'b1; state <= ENC;
        end else state <= FIN;
      end
      FIN: begin done <= 1'b1; state <= IDLE; end
      default: state <= IDLE;
    endcase
  end
endmodule
`default_nettype wire
"""


def generate_chip(cfg: RTLConfig, top="hdc_chip", core="approxhdc_top", iow=32):
    """Pad-limited chip top for the physical flow: the verified core plus a narrow load port.

    The core's ring load/readout bus is C*P*WS bits wide (hundreds of pins). The chip instead
    stages one ring word through an iow-bit shift register (ld_shift), then commits it with
    load_we. Readout pins and debug outputs are not brought out; pred/done/learned are.
    """
    WS = cfg.w if cfg.learn else 1
    RW = cfg.C * cfg.P * WS
    LQ, LF, AW = _clog2(cfg.Q), _clog2(cfg.F), int(math.log2(cfg.D)) + 1
    nchunk = math.ceil(RW / iow)
    stage = (f"stage <= {{ld_data, stage[{nchunk * iow - 1}:{iow}]}};" if nchunk > 1
             else "stage <= ld_data;")
    if cfg.cg:
        stage_always = f"wire gclk_stage;\n  hdc_cg u_cg_stage (.clk(clk), .en(ld_shift), .gclk(gclk_stage));\n  always @(posedge gclk_stage) {stage}"
    else:
        stage_always = f"always @(posedge clk) if (ld_shift) {stage}"
    return generate(cfg, core) + f"""
// Chip top: {nchunk} x {iow}-bit chunks fill one {RW}-bit ring word.
module {top} (
  input  wire            clk,
  input  wire            rst,
  input  wire            start,
  input  wire            learn,
  input  wire            upd_err,
  input  wire [2:0]      label,
  input  wire            feat_we,
  input  wire [{LF-1}:0] feat_addr,
  input  wire [{LQ-1}:0] feat_data,
  input  wire            ld_shift,
  input  wire [{iow-1}:0] ld_data,
  input  wire            load_we,
  output wire            busy,
  output wire            done,
  output wire [2:0]      pred,
  output wire            learned
);
  reg [{nchunk * iow - 1}:0] stage;
  {stage_always}
  wire [{RW-1}:0] unused_head;
  wire [{cfg.C * AW - 1}:0] unused_dist;
  wire [{cfg.P - 1}:0] unused_q;
  wire unused_c, unused_p;
  {core} u_core (
    .clk(clk), .rst(rst), .start(start), .learn(learn), .upd_err(upd_err), .label(label),
    .feat_we(feat_we), .feat_addr(feat_addr), .feat_data(feat_data),
    .load_we(load_we), .rot(1'b0), .load_data(stage[{RW-1}:0]), .head(unused_head),
    .busy(busy), .done(done), .pred(pred), .learned(learned), .dist_flat(unused_dist),
    .dbg_q(unused_q), .dbg_commit(unused_c), .dbg_pass2(unused_p));
endmodule
"""


def write(cfg, path, top="approxhdc_top"):
    with open(path, "w") as fh:
        fh.write(generate(cfg, top))
    return path


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    for fld, default in asdict(RTLConfig()).items():
        ap.add_argument(f"--{fld}", type=type(default), default=default)
    ap.add_argument("-o", "--out", default=None)
    a = vars(ap.parse_args())
    out = a.pop("out")
    cfg = RTLConfig(**a)
    write(cfg, out or f"{cfg.name}.v")
    print(out or f"{cfg.name}.v")
